   - name: check if keystore all ready exists
     stat:
        path:  /var/mqm/{{ QMGR_NAME }}/ssl/{{ KEYFILE_NAME }}
     register: KEYFILE

   - name: fail if exists
     fail:
        msg: keyfile already exists
     when: KEYFILE.stat.exists

   - name: create keystore 
     shell: "{{ MQ_DIR }}/bin/runmqakm -keydb -create -db /var/mqm/qmgrs/{{ QMGR_NAME }}/ssl/{{ KEYFILE_NAME }} -type kdb -stash -genpw -empty"
     become: yes
     become_user: mqm

