      - name: Check OS
        fail:
           msg: This playbook only runs on Linux, found {{ os_family }}
        when: ansible_system != "Linux"

      - name: Copy file to remote system
        copy:
          src: "{{ MQ_FILE_NAME }}"
          dest: /tmp/{{ MQ_FILE_NAME | basename }}

      - name: Check if file exists
        stat:
          path: /tmp/{{ MQ_FILE_NAME | basename }}
        register: MQFile

      - name: fail when MQ Files does not exist
        fail:
          msg: Missing MQ Archive - {{ MQ_FILE_NAME | basename }}
        when: MQFile.stat.exists == false

      - name: Uncompress MQ
        unarchive:
           src: /tmp/{{ MQ_FILE_NAME | basename }}
           dest: /tmp/
           remote_src: true
        when: '"tar" in MQ_FILE_NAME or "gz" in MQ_FILE_NAME'

      - name: check if MQ may be installed
        stat:
          path: /opt/mqm/bin/dspmqver
        register: MQDSPVER

      - include_tasks: stop_qmgrs.yaml
        when: MQDSPVER.stat.exists == true

      - name: get a list of RPM files
        find: 
           file_type: file
           patterns: "*rpm,*deb"
           paths: /tmp/MQServer
        register: RPMS

      - name : MQ_default_install - Install MQ pakages using yum
        become: yes
        yum:
           name:  "{{ RPMS.files | map(attribute='path') | list }}"
           state: present
           disable_gpg_check: True
           use_backend: yum4
        when: ansible_distribution == 'RedHat'

      - name : MQ_default_install - Install MQ pakages using apt
        become: yes
        become_method: sudo
        shell: "apt install -y /tmp/MQServer/*.deb"
        when: ansible_distribution == 'Ubuntu'

      - name: accept MQ License
        shell: /opt/mqm/bin/mqlicense -accept 

      - name: Delete temp directory
        file:
           state: absent
           path: /tmp/MQServer
