   - name: check if QMGR exists
     shell: /{{ MQ_DIR }}/bin/dspmq -m {{ QMGR_NAME }}
     become: yes
     become_user: mqm

   - include_tasks: stop_single_qmgr.yaml

   - name: Delete current files
     file:
        state: absent
        path: "{{ item }}"
     with_items:
        - /var/mqm/qmgrs/{{ QMGR_NAME }}
        - /var/mqm/log/{{ QMGR_NAME }}

   - name: Check if the file is only a tar
     stat:
        path: "{{ BACKUP_DIR }}/{{ QMGR_RESTORE_NAME }}.tar"
     register: ONLY_TAR 

   - name: Unarchive MQ
     shell: gzip -d {{ BACKUP_DIR }}/{{ QMGR_RESTORE_NAME }}.tgz
     when: not ONLY_TAR.stat.exists

   - name: Unarchive MQ
     shell: tar -xvf {{ BACKUP_DIR }}/{{ QMGR_RESTORE_NAME }}.tar -C /var/mqm/
     become: yes
     become_user: mqm 

   - include_tasks: start_single_qmgr.yaml
