   - name: check if QMGR exists
     shell: /{{ MQ_DIR }}/bin/dspmq -m {{ QMGR_NAME }}
     become: yes
     become_user: mqm

   - name: check QMGR state
     shell: /{{ MQ_DIR }}/bin/dspmq -m {{ QMGR_NAME }} | grep -vi Ended | awk '{print $1}' | sed 's/.*(\(.*\))/\1/'
     become: yes
     become_user: mqm
     register: QMGRS

   - name: Stop QMGR
     shell: /{{ MQ_DIR }}/bin/endmqm -i {{ item }}
     become: yes
     become_user: mqm
     with_items: "{{ QMGRS.stdout_lines }}"
