      - name: Check OS
        fail:
           msg: This playbook only runs on Linux, found {{ os_family }}
        when: ansible_system != "Linux"

      - name: check if MQ may be installed
        stat:
          path: /usr/mqm/bin/dspmqver
        register: MQDSPVER

      - include_tasks: stop_qmgrs.yaml
        when: MQDSPVER.stat.exists == true

      - name :  list installed MQ packages
        become: yes
        yum:
          list: "MQSeries*"
        register: RPMS
        when: ansible_distribution == 'RedHat'

      - name :  list installed MQ packages
        become: yes
        shell: "dpkg -l | grep ibmmq | awk '{print $2}'"
        register: RPMS
        when: ansible_distribution == 'Ubuntu'

      - name :  Uninstall MQ pakages using yum
        become: yes
        yum:
           name:  "{{ RPMS.results | map(attribute='name') | list }}"
           state: absent
        when: ansible_distribution == 'RedHat'

      - name :  Uninstall MQ pakages using dpkg
        become: yes
        shell: "dpkg -P {{ RPMS.stdout_lines | join(' ') }}"
        when: ansible_distribution == 'Ubuntu'
