 - name: Clear Queues
   hosts: localhost
   gather_facts: yes
   become: yes

   tasks:

   - name: Check if QMGR name is passed
     fail:
        msg: No QMGR_NAME passed in the parameters
     when: QMGR_NAME is not defined

   - name: Check if Queues name is passed
     fail:
        msg: No QUEUE_NAMES passed in the parameters
     when: QUEUE_NAMES is not defined

   - name: set MQ Directory
     set_fact:
        MQ_DIR: "{{ (ansible_system == 'AIX') | ternary ('/usr/mqm', '/opt/mqm') }}"

   - include_tasks: ../tasks/clear_queues.yaml
