 - name: Create QMGR
   hosts: localhost
   gather_facts: yes
   become: yes

   tasks:

   - name: Check if QMGR name is passed
     fail:
        msg: No QMGR_NAME passed in the parameters
     when: QMGR_NAME is not defined

   - name: set MQ Directory
     set_fact:
        MQ_DIR: "{{ (ansible_system == 'AIX') | ternary ('/usr/mqm', '/opt/mqm') }}"

   - include_tasks: ../tasks/create_qmgr.yaml
   - include_tasks: ../tasks/start_single_qmgr.yaml
   - include_tasks: ../tasks/configure_qmgr.yaml

