 - name: Install MQ
   hosts: localhost
   gather_facts: yes
   become: yes

   tasks:

      - include_tasks: ../tasks/install_mq_aix.yaml
        when: ansible_system == "AIX"

      - include_tasks: ../tasks/install_mq_linux.yaml
        when: ansible_system == "Linux"
