 - name: Restore MQ
   hosts: localhost
   gather_facts: yes
   become: yes

   vars:
      BACKUP_DIR: "/tmp/backups"

   tasks:

   - name: Check if QMGR name is passed
     fail:
        msg: No QMGR_NAME passed in the parameters
     when: QMGR_NAME is not defined

   - name: Check if restore file name is passed
     fail:
        msg: No QMGR_RESTORE_NAME passed in the parameters
     when: QMGR_RESTORE_NAME is not defined

   - name: set MQ Directory
     set_fact:
        MQ_DIR: "{{ (ansible_system == 'AIX') | ternary ('/usr/mqm', '/opt/mqm') }}"

   - include_tasks: ../tasks/restore_config_qmgr.yaml
   - include_tasks: ../tasks/restore_data_qmgr.yaml

